# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /media/manuel/ExtraDrive1/URL/Hardware_Arquitecturas/Labs/MIPSfpga_Labs_v2.0/MIPSfpga_Labs/Labs/Xilinx/Part1_Intro/Lab01_Vivado/Project_1/Project_1.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xci
# IP: The module: 'clk_wiz_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /media/manuel/ExtraDrive1/URL/Hardware_Arquitecturas/Labs/MIPSfpga_Labs_v2.0/MIPSfpga_Labs/Labs/Xilinx/Part1_Intro/Lab01_Vivado/Project_1/Project_1.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /media/manuel/ExtraDrive1/URL/Hardware_Arquitecturas/Labs/MIPSfpga_Labs_v2.0/MIPSfpga_Labs/Labs/Xilinx/Part1_Intro/Lab01_Vivado/Project_1/Project_1.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /media/manuel/ExtraDrive1/URL/Hardware_Arquitecturas/Labs/MIPSfpga_Labs_v2.0/MIPSfpga_Labs/Labs/Xilinx/Part1_Intro/Lab01_Vivado/Project_1/Project_1.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: /media/manuel/ExtraDrive1/URL/Hardware_Arquitecturas/Labs/MIPSfpga_Labs_v2.0/MIPSfpga_Labs/Labs/Xilinx/Part1_Intro/Lab01_Vivado/Project_1/Project_1.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xci
# IP: The module: 'clk_wiz_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /media/manuel/ExtraDrive1/URL/Hardware_Arquitecturas/Labs/MIPSfpga_Labs_v2.0/MIPSfpga_Labs/Labs/Xilinx/Part1_Intro/Lab01_Vivado/Project_1/Project_1.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /media/manuel/ExtraDrive1/URL/Hardware_Arquitecturas/Labs/MIPSfpga_Labs_v2.0/MIPSfpga_Labs/Labs/Xilinx/Part1_Intro/Lab01_Vivado/Project_1/Project_1.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /media/manuel/ExtraDrive1/URL/Hardware_Arquitecturas/Labs/MIPSfpga_Labs_v2.0/MIPSfpga_Labs/Labs/Xilinx/Part1_Intro/Lab01_Vivado/Project_1/Project_1.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
